production:
  app: jit-blog-sandbox
  stack: cedar
  config:
    BUNDLE_WITHOUT: "development:test"
    DOMAIN_NAME: jit-blog-sandbox.herokuapp.com
    TZ: "Asia/Tokyo"
  addons: &default_addons
    - heroku-postgresql
    - pgbackups:auto-month
    - papertrail
    - newrelic

staging:
  stack: cedar
  app: jit-blog-sandbox-staging
  config:
    BUNDLE_WITHOUT: "development:test"
    TZ: "Asia/Tokyo"
    RAILS_ENV: staging
    RACK_ENV: staging
    DOMAIN_NAME: jit-blog-sandbox-staging.herokuapp.com
  addons: *default_addons
